cxx_library(
  name = 'freetype',
  header_namespace = '',
  exported_headers = [
    'imgui_freetype.h',
  ],
  srcs = [
    'imgui_freetype.cpp',
  ],
  deps = [
    '//:imgui',
  ],
  visibility = [
    'PUBLIC',
  ],
)
