manifest = "6d3f8956c331efa198abcc290fa56aec63b73cb8076eeb3addfd31a36cfe36ac"

[[dependency]]
package = "github.com/buckaroo-pm/glfw"
target = "//:glfw"

[[dependency]]
package = "github.com/buckaroo-pm/host-opengl"
target = "//:opengl"

[[dependency]]
package = "github.com/buckaroo-pm/pkg-config-gl"
target = "//:gl"

[lock."github.com/buckaroo-pm/glfw"]
versions = [ "branch=master" ]
revision = "9ad6969265c672fcff1ca6c90d9ffd27400896e5"

[lock."github.com/buckaroo-pm/host-cocoa"]
versions = [ "branch=master" ]
revision = "72ea2945d7e139d9f4803c726339778e619b8cdb"

[lock."github.com/buckaroo-pm/host-core-foundation"]
versions = [ "branch=master" ]
revision = "fd7081ffe1244afb86c41c2d41d3603f851feae8"

[lock."github.com/buckaroo-pm/host-core-video"]
versions = [ "branch=master" ]
revision = "65639f49f1a4836f0f3b31503ebad8c9c2a73a71"

[lock."github.com/buckaroo-pm/host-dl"]
versions = [ "branch=master" ]
revision = "69a239353756c2ef5c97e5a56a0964fb7ac6eb49"

[lock."github.com/buckaroo-pm/host-io-kit"]
versions = [ "branch=master" ]
revision = "68cf79a5a0cecfb6d68896ad29d3b0c001849dd5"

[lock."github.com/buckaroo-pm/host-opengl"]
versions = [ "branch=master" ]
revision = "183de5e5057c37c69dc5d298781b3c131a3688e4"

[lock."github.com/buckaroo-pm/host-pthread"]
versions = [ "branch=master" ]
revision = "a62519aa69c8e3243d6065fbf4c1d2de072f86f6"

[lock."github.com/buckaroo-pm/pkg-config-gl"]
versions = [ "branch=master" ]
revision = "c8734a6884d0aaa713c059673a103fe58de08084"

[lock."github.com/buckaroo-pm/pkg-config-x11"]
versions = [ "branch=master" ]
revision = "6f292a6166cd3c45c776b294485a24e7d71c0e0c"
